### ISSUE TITLE
some data don't work

### ISSUE THREAD

**Issue by zhengfangxin** [jaidevd/pyhht#29] opened 2017-05-16 08:29 UTC
### this code can't  work
```
from pyhht.emd import EMD
from pyhht.visualization import plot_imfs
import numpy as np

x = [2275.4, 2274.6, 2274.6, 2274.4, 2274.0, 2273.6, 2272.8, 2273.6, 2274.0, 2273.4, 2273.0, 2272.8, 2272.4, 2272.4, 2272.6, 2271.8, 2269.4, 2269.8, 2270.0, 2269.6, 2269.0, 2267.4, 2267.6, 2268.0, 2268.4, 2268.0, 2268.2, 2268.0, 2267.6, 2267.8, 2267.6, 2265.2, 2265.0, 2264.0, 2263.2, 2262.4, 2263.8, 2263.2, 2263.0, 2261.4, 2263.0, 2263.0, 2262.8, 2262.4, 2262.4, 2263.6, 2262.8, 2262.6, 2261.2, 2258.2, 2258.8, 2258.4, 2259.4, 2258.4, 2258.0, 2257.0, 2257.0, 2257.0, 2256.8, 2255.4, 2256.2, 2256.2, 2256.8, 2255.4, 2256.6, 2256.2, 2255.0, 2256.0, 2256.4, 2257.0, 2255.8, 2256.6, 2257.0, 2255.6, 2254.0, 2253.6, 2255.0, 2255.2, 2254.2, 2255.2, 2255.0, 2256.4, 2256.2, 2256.8, 2256.2, 2256.4, 2257.0, 2256.6, 2256.2, 2256.6, 2256.4, 2256.0, 2255.2, 2254.6, 2254.2, 2254.4, 2253.4, 2251.6, 2250.4, 2251.6, 2252.6, 2252.6, 2252.8, 2251.4, 2252.4, 2253.2, 2252.6, 2252.8, 2253.0, 2253.2, 2253.8, 2253.2, 2253.4, 2253.4, 2253.4, 2254.8, 2253.8, 2253.4, 2253.8, 2254.0, 2253.4, 2253.0, 2253.8, 2253.4, 2253.2, 2253.4, 2253.8, 2253.0, 2252.4, 2252.2, 2252.0, 2251.2, 2252.4, 2253.8, 2254.0, 2253.6, 2253.2, 2251.8, 2251.0, 2251.6, 2251.6, 2250.4, 2252.0, 2250.6, 2251.0, 2251.4, 2251.2, 2251.6, 2252.2, 2252.0, 2252.0, 2252.4, 2252.6, 2252.4, 2251.4, 2251.8, 2251.0, 2251.4, 2252.2, 2252.0, 2253.0, 2252.6, 2253.4]
x = np.array(x)
t = np.array([i for i in range(len(x))])
decomposer = EMD(x)
imfs = decomposer.decompose()

plot_imfs(x, imfs, t)
```

**Comment by jaidevd** [comment] 2017-05-26 12:01
Thanks @zhengfangxin for the bug report. I'll look into it over the weekend. When I tried to reproduce this, I can only see the plot of the original signal, but no IMFs are plotted. Is that the problem you are facing?

**Comment by LeilaK90** [comment] 2017-06-01 13:12
How i can  change the number of n_imfs for extract 15 imfs Please?

**Comment by jaidevd** [comment] 2017-06-19 14:03
Hi @zhengfangxin 
After some initial debugging it seems that the problem is because the signal is not well sampled. For undersampled signals (i.e. when the data between neighbouring indices varies too much), the envelop splines come up with too much energy, so much that they overwhelm the signal itself. PyHHT should have tools to deal with such data. One way would be to detect the undersampling beforehand and upsample the signal by adding dummy values between neighbouring samples.
Let me see what I can do.

**Comment by jaidevd** [comment] 2017-06-19 14:04
@LeilaK90 When you create the `EMD` object, you can specify how many IMFs you want, like so:
```python
emd = EMD(x, n_imfs=15)
```

**Comment by woj-evan** [comment] 2017-06-22 17:54
Hi @jaidevd,
I have been encountering the same problem where only the original signal is plotted, and nothing is shown for the IMFs as if they don't exist/weren't calculated at all. Following up on your comment about the sampling, do you have any other recommendations about fixing this issue without upsampling the raw data? Increasing the size of the input data is a step backwards in the process I am trying to undertake.

**Comment by jaidevd** [comment] 2017-06-23 08:46
Hi @ewojcie2 
On further debugging I've realized that I was wrong. This has nothing to do with sampling rate. The interpolation problems are happening because by default, pyhht tries to extend the signal beyond its boundaries so as to make sure that the signal, even at its endpoints, lies fully within the envelopes. I'm going to try out a couple of ways of fixing this:
1. Make the extrapolation optional
2. Even if it is forced, pyhht should have a way of detecting this problem, and suggesting to the user that this should be disabled.

I'll check this out over the weekend.

**Comment by jaidevd** [comment] 2017-06-23 12:37
Sorry didn't mean to close just yet.

**Comment by jaidevd** [comment] 2017-06-23 12:48
Hi @zhengfangxin and @ewojcie2 
This should be fixed (https://github.com/jaidevd/pyhht/pull/34) now. Please pull from the master branch and try again as follows:
```python
emd = EMD(x, nbsym=False)
imfs = emd.decompose()
plot_imfs(x, imfs)
```
Note that setting the `nbsym` parameter to `False` is important for signals like this one.
Now I'm not sure what is it about this signal that is causing the sifting to break, but I've added a follow-up issue to investigate further (see #35 )

Thanks

**Closed as completed by jaidevd** 2017-06-23 12:48 UTC

**Comment by woj-evan** [comment] 2017-06-23 13:31
Hi agani @jaidevd 
Thank you for the fast update, this seems to have fixed the issue with the data I was use. I'll keep testing with similar data sets and see if this fix works more generally. Your dedication is appreciated.
