### ISSUE TITLE
"ValueError: setting an array element with a sequence," and array size too big?

### ISSUE THREAD

**Issue by shawyun** [jaidevd/pyhht#13] opened 2015-10-07 03:03 UTC
I am coming across a specific error, "ValueError: setting an array element with a sequence." It shows up after the 2000th iteration, which I know is the set default. I tried changing the default number of iterations in the emd.py file for a quick fix, but it continues to just do 2000 iterations as a max.

My main issue is not the number of iterations, but rather why I am getting the error, "ValueError: setting an array element with a sequence." The main difference between the GitHub example and my analysis was that I was reading my signal data from a csv file.

I made sure the data sets were put into arrays, similar to the example involving modes=sin(2_pi_5_t)+sin(2_pi_10_t). Could it be that there are too many points in the csv file for "pyhht" to handle? The length of the array created by the CSV file is about 38200.

**Comment by jaidevd** [comment] 2015-10-07 14:38
Thanks @shawyun, I'll take a look over the weekend.

**Comment by shawyun** [comment] 2015-10-07 23:40
Sounds good, let me know if there is a way I can help.

Best of Luck,
Shawyun

**Comment by imcbrear** [comment] 2016-06-30 23:16
Was this error ever solved? I seem to be running into the same issue...

Thanks,
Ian

**Comment by jaidevd** [comment] 2016-07-01 06:10
@shawyun @imcbrear I'm sorry, I totally forgot about this. I'll look into this now. So it seems to me that there are two issues here. Thanks, @imcbrear for bringing this back up.
1. We can't change the maximum number of iterations, the script just keeps doing 2000 iterations even if we want it to stop earlier.
2. When the sifting reaches the 2000th iteration, it throws the traceback:

```
ValueError: setting an array element with a sequence.
```

Is this right? Correct me if I am wrong. Also, can either of you show me the exact steps to reproduce this error? If you can share the data and the code you are using, that would be ideal.

Thanks

**Comment by imcbrear** [comment] 2016-07-02 02:04
@jaidevd Hi thanks for getting back to me. Sure thing. Here's an example where the decomposition seems to work for a number of modes, but then fails. (On some other examples I did before, it would fail right away- not after a series of outputs..) 

Obviously the problem might just be that this time series is too big (or have to much bandwidth?). But I wasn't aware whether or not your algorithms were supposed to be applicable for arbitrary time series, or only time series meeting a certain criteria (i.e. limited bandwidth/number of samples). The below example works if you cut the trace around the larger waveform (to around 30000 samples).

`from pyhht.emd import EMD`
`d = np.load('testdata.npy')`
`l = EMD(d)`
`ll = l.decompose()`

output:

Mode 2, Iteration 600
6 minima > 0; 61600 maxima < 0.
Mode 2, Iteration 800
5 minima > 0; 63146 maxima < 0.
Mode 2, Iteration 1000
1 minima > 0; 63911 maxima < 0.
Mode 3, Iteration 1200
0 minima > 0; 36502 maxima < 0.
Mode 3, Iteration 1400
5 minima > 0; 37039 maxima < 0.
Mode 3, Iteration 1600
0 minima > 0; 37394 maxima < 0.
Mode 3, Iteration 1800
0 minima > 0; 37596 maxima < 0.

`ValueError: setting an array element with a sequence.`

[testdata.npy.zip](https://github.com/jaidevd/pyhht/files/344353/testdata.npy.zip)

**Comment by jaidevd** [comment] 2016-07-02 06:38
Perfect, I can reproduce the error. Thanks, @imcbrear

**Comment by jaidevd** [comment] 2016-07-04 07:49
Hi @imcbrear, @shawyun 

The issue is fixed for now. I was a matter of incorrect array concatenation and bad stopping criteria for the sifting. You can pull the code from this branch: https://github.com/jaidevd/pyhht/tree/jd-fix-issue13,
install pyhht again, and it should work.

However, I'll be adding tests for avoiding such problems to the same branch over the next two days. And till then I intend to keep this issue open. I'll notify you when that happens, and then you can start using the stable (dev branch) code again.

Thanks

**Comment by jaidevd** [comment] 2016-07-04 09:15
@imcbrear @shawyun Please install from the dev branch and try again. The issue should be fixed.

**Closed as completed** 2016-07-04 09:14 UTC

**Comment by imcbrear** [comment] 2016-07-05 21:45
Thanks!
